def __exit__(self, *args):
    u'Called at the end of the ``with ...`` statement.'
    self.close()
    assert (len(args) == 3)
    return False
