{
  if (!hasException())   setException(ex);
  self_cancel1();
  if (_nleft != null)   try {
    _nleft.get();
  }
 catch (  Throwable _) {
  }
  _nleft=null;
  if (_nrite != null)   try {
    _nrite.get();
  }
 catch (  Throwable _) {
  }
  _nrite=null;
  return super.onExceptionalCompletion(ex,caller);
}
